### ISSUE TITLE
Server side

### ISSUE THREAD

**Issue by alex5219** [ImranDoet/superheroesaddon#2]
https://github.com/ImranDoet/superheroesaddon/blob/aad60a90c847538bc95eaef380a28610abe397fe/src/main/java/me/imrandoet/superheroesaddon/common/abilities/AbilityColdBreath.java#L37

Have you tested this on the server side? I tried it out my version of this on a server and it didn't work lol. Was wondering if you could see if yours works.

**Comment by ImranDoet** [comment]
What exactly doesnt work? I know it's a common bug that if player A has for example a addon and server A, the server player A is joining, doesn't have the addon, it's not going to work.

**Comment by alex5219** [comment]
The check for Superman’s frost breath is on client side so the server kicks you.
