### ISSUE TITLE
Few bugs/glitches

### ISSUE THREAD

**Issue by Azinthos** [ImranDoet/superheroesaddon#4]
**Aquaman Bugs/Glitches**
*Not being able to breathe in water

**Spider-Man Bugs/Glitches**
Spider-Sense doesn't work

**Kryptonite doesn't get rid of Superman's abilities.**

**Comment by GiantVideoGamer** [comment]
Ultron has no texture he is only pink and black

**Comment by BuddermanTheAmazing** [comment]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: fiskfille/heroes/client/trail/TrailType

**Comment by ImranDoet** [comment]
Format to use from now on:

**Bug Description: **
**Evidence/Proof: (Video or screenshot)**

Try to explain the bug very detailed and post much proof so I can resolve the issue asap!
